# -*- coding: utf-8 -*-
"""Copy of blip-image-captioning-large.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nAYs-IgvPdOXT5yJN5h_0LVgLyFXr6RP
"""

import secrets
import string

def generate_strong_password(length):
    # Define sets
    letters = string.ascii_letters
    digits = string.digits
    symbols = string.punctuation

    # Guarantee at least one of each
    password = [
        secrets.choice(letters),
        secrets.choice(digits),
        secrets.choice(symbols)
    ]

    # Fill the rest of the length
    all_chars = letters + digits + symbols
    password += [secrets.choice(all_chars) for _ in range(length - 3)]

    # Shuffle to ensure the first three aren't predictable
    secrets.SystemRandom().shuffle(password)

    return "".join(password)

password = generate_strong_password(12)
print(f"Generated strong password: {password}")